samples/config/routes.rb
ButtonManagerSamples::Engine.routes.draw do
  match "button_manager(/:action)",  :controller => "button_manager", :as => :button_manager
  root :to => "button_manager#index"
end

samples/app/models/button_manager_samples/api_form_builder.rb
module ButtonManagerSamples
  class APIFormBuilder < SimpleForm::FormBuilder
    def fields_for(member_name, member_object = nil, &block)
      member_object ||= ( object.send(member_name) || object.send("#{member_name}=", {}))
      member_options = object.class.members[member_name.to_sym]
      if member_options[:array]
        fields = []
        member_object.each_with_index do |obj, index|
          fields << super(member_name, obj, :index => index, &block)
        end
        fields.join.html_safe
      else
        super(member_name, member_object, &block)
      end
    end
    alias_method :simple_form_for, :fields_for
    alias_method :association, :fields_for

    def input(member_name, options = {})
      super(member_name, api_input_options(member_name, options))
    end

    def api_input_options(member_name, options = {})
      member_options      = object.class.members[member_name.to_sym]
      options[:label]   ||= member_name.to_s.underscore.humanize
      options[:wrapper] ||= :api_sample_form
      options[:required]  = !!member_options[:required] if options[:required].nil?
      if member_options[:type] < PayPal::SDK::Core::API::DataTypes::Enum
        options[:as] = ( member_options[:array] ? :check_boxes : :select )
        options[:collection] = member_options[:type].options
      elsif member_options[:type] == PayPal::SDK::Core::API::DataTypes::SimpleTypes::Boolean
        options[:as] = :select
        options[:collection] = [ true, false ]
      end
      options
    end
  end
end

samples/app/controllers/button_manager_samples/application_controller.rb
module ButtonManagerSamples
  class ApplicationController < ActionController::Base

    def default_api_value
      t("#{service_name}.#{service_action}", :default => {})
    end

    def service_name
      params[:controller].gsub(/^.*\//, "")
    end

    def service_action
      params[:action]
    end
    helper_method :service_action, :service_name

  end
end

samples/app/controllers/button_manager_samples/button_manager_controller.rb
require_dependency "button_manager_samples/application_controller"

module ButtonManagerSamples
  class ButtonManagerController < ApplicationController
    include PayPal::SDK::ButtonManager

    def index
      redirect_to :action => :bm_create_button
    end

    def ipn_notify
      if api.ipn_valid?(request.raw_post)
        logger.info("IPN message: VERIFIED")
        render :text => "VERIFIED"
      else
        logger.info("IPN message: INVALID")
        render :text => "INVALID"
      end
    end

    def bm_create_button
      @bm_create_button = api.build_bm_create_button(params[:BMCreateButtonRequestType] || default_api_value)
      if params[:ButtonVar]
        @button_var = params[:ButtonVar]
        @bm_create_button.ButtonVar = @button_var.map{|key, val| "#{key}=#{val}" }
      else
        @button_var = {}
        @bm_create_button.ButtonVar.each do |str|
          ary = str.split("=", 2)
          @button_var.merge! ary[0] => ary[1]
        end
        @button_var["return"] ||= button_manager_url(:bm_create_button)
        @button_var["notify_url"] ||= button_manager_url(:ipn_notify)
      end
      @bm_create_button_response = api.bm_create_button(@bm_create_button) if request.post?
    end

    def bm_update_button
      @bm_update_button = api.build_bm_update_button(params[:BMUpdateButtonRequestType] || default_api_value)
      @bm_update_button_response = api.bm_update_button(@bm_update_button) if request.post?
    end

    def bm_manage_button_status
      @bm_manage_button_status = api.build_bm_manage_button_status(params[:BMManageButtonStatusRequestType] || default_api_value)
      @bm_manage_button_status_response = api.bm_manage_button_status(@bm_manage_button_status) if request.post?
    end

    def bm_get_button_details
      @bm_get_button_details = api.build_bm_get_button_details(params[:BMGetButtonDetailsRequestType] || default_api_value)
      @bm_get_button_details_response = api.bm_get_button_details(@bm_get_button_details) if request.post?
    end

    def bm_set_inventory
      @bm_set_inventory = api.build_bm_set_inventory(params[:BMSetInventoryRequestType] || default_api_value)
      @bm_set_inventory_response = api.bm_set_inventory(@bm_set_inventory) if request.post?
    end

    def bm_get_inventory
      @bm_get_inventory = api.build_bm_get_inventory(params[:BMGetInventoryRequestType] || default_api_value)
      @bm_get_inventory_response = api.bm_get_inventory(@bm_get_inventory) if request.post?
    end

    def bm_button_search
      @bm_button_search = api.build_bm_button_search(params[:BMButtonSearchRequestType] || default_api_value)
      @bm_button_search_response = api.bm_button_search(@bm_button_search) if request.post?
    end

    private

    def api
      @api ||= API.new
    end
  end
end

samples/app/helpers/button_manager_samples/application_helper.rb
module ButtonManagerSamples
  module ApplicationHelper
    def active_li(display, link_path, options = {})
      active_menu = options.delete(:match_path) ? request.path =~ Regexp.new(link_path) : request.path == link_path
      content_tag(:li, :class => active_menu ? "active" : "") do
        link_to(display, link_path, options)
      end
    end

    def active_li_regexp(display, link_path, options = {})
      active_li(display, link_path, options.merge(:match_path => true))
    end

    def api_form_for(object, *args, &block)
      options         = args.extract_options!
      options[:as]  ||= api_class_name(object.class)
      simple_form_for(object, *(args << options.merge(:builder => APIFormBuilder, :wrapper => :api_sample_form)), &block)
    end

    def generate_code(api_request, api_response)
      request_hash= api_request.to_hash(:namespace => false, :attribute => false)
      request_hash.delete("Version")
      # request_hash  = get_dotted_hash(request_hash)
      response_hash = api_response.to_hash(:namespace => false, :attribute => false)
      ruby_code   = render("ruby_code.rb", :api_request => api_request, :api_response => api_response,
                       :request_hash => request_hash, :response_hash => response_hash)
      ruby_code.html_safe
    end

    def get_dotted_hash(hash, prefix = "", values = {})
      max_lenght  = max_key_length(hash)
      hash.each do |key, value|
        if value.is_a? Hash
          get_dotted_hash(value, "#{prefix}#{key}.", values)
        elsif value.is_a? Array and value[0].is_a? Hash
          value.each_with_index do |array_value, index|
            get_dotted_hash(array_value, "#{prefix}#{key}[#{index}].", values)
          end
        elsif !value.nil?
          k = sprintf("%s%-#{max_lenght}s", prefix, key)
          values[k] = value
        end
      end
      values
    end

    def max_key_length(hash)
      hash.select{|k, v| !(v.is_a? Hash or ( v.is_a? Array and v[0].is_a? Hash )) }.map{|k,v| k.size}.max
    end

    def format_hash(hash)
      entries = hash.map do |key, value|
        "#{key.to_sym.inspect} => " +
          if value.is_a? Hash and value.size > 0
            format_hash(value)
          elsif value.is_a? Array and value[0].is_a? Hash
            "[" + value.map{|v| format_hash(v) }.join(",") + "]"
          else
            value.to_json
          end
      end
      indent_hash_entries(entries)
    end

    def indent_hash_entries(entries)
      if entries.size > 0
        "{\n" + entries.join(",\n").gsub(/^/, "  ") + " }"
      else
        "{}"
      end
    end

    def api_class_name(klass)
      klass.name.gsub(/^.*::/, "")
    end
  end
end

samples/app/helpers/button_manager_samples/button_manager_helper.rb
module ButtonManagerSamples
  module ButtonManagerHelper
  end
end

samples/app/views/button_manager_samples/application/_api_response.html.haml
%div#response
  %p
    %b Ruby Code:
    = find_and_preserve CodeRay.scan(generate_code(request, response), "ruby").div.html_safe
  %p
    %b Response:
    = find_and_preserve CodeRay.scan(format_hash(response.to_hash(:attribute => false, :namespace => false)), "ruby").div.html_safe

samples/app/views/button_manager_samples/application/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .pull-right
        = link_to "Source on GitHub", "https://github.com/paypal/buttonmanager-sdk-ruby", :class => "btn btn-small"
        %span.btn.btn-info.btn-small.disabled Click Submit to Generate Code !
      %a.brand{:href => "#"} PayPal SDK
      .nav-collapse.collapse
        %ul.nav
          = active_li_regexp "Button Manager", button_manager_path

samples/app/views/button_manager_samples/application/_ruby_code.rb.erb
require 'paypal-sdk-<%= service_name.gsub("_", "") %>'
@api = PayPal::SDK::<%= service_name.camelize %>::API.new

# Build request object
@<%= service_action %> = @api.build_<%= service_action %>(<%= format_hash(request_hash).html_safe %>)

# Make API call & get response
@<%= service_action %>_response = @api.<%= service_action %>(@<%= service_action %>)

# Access Response
if @<%= service_action %>_response.success?
<% api_response.members.keys.each do |key| -%>
  <% unless [ :Timestamp, :Version, :Build, :type, :Ack, :xmlns, :CorrelationID, :Errors ].include? key -%>
  @<%= service_action %>_response.<%= key %>
  <% end -%>
<% end -%>
else
  @<%= service_action %>_response.Errors
end

samples/app/views/button_manager_samples/application/_sidebar.html.erb
<ul class="nav nav-list bs-docs-sidenav ">
  <%= active_li "Home",  "/" %>
</ul>

samples/app/views/button_manager_samples/application/_token.html.haml
%legend Autherization
.control-group.string.optional
  = label_tag :token, "Token", :class => "string optional control-label"
  .controls
    = text_field_tag :token, params[:token] || @api.config.token

.control-group.string.optional
  = label_tag :token_secret, "Token Secret", :class => "string optional control-label"
  .controls
    = text_field_tag :token_secret, params[:token_secret] || @api.config.token_secret

samples/app/views/button_manager_samples/button_manager/_sidebar.html.haml
.well.well-mini
  %ul.nav.nav-list.bs-docs-sidenav
    = active_li "Create button",         button_manager_path(:bm_create_button)
    = active_li "Manage button status",  button_manager_path(:bm_manage_button_status)
    = active_li "Get button details",    button_manager_path(:bm_get_button_details)
    = active_li "Button search",         button_manager_path(:bm_button_search)
    = active_li "Set inventory",         button_manager_path(:bm_set_inventory)
    = active_li "Get inventory",         button_manager_path(:bm_get_inventory)

samples/app/views/button_manager_samples/button_manager/bm_button_search.html.haml
= api_form_for @bm_button_search, :url => button_manager_path(:bm_button_search) do |f|

  .row
    .span5
      %legend Button search request
      = f.input :StartDate
      = f.input :EndDate

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bm_button_search_response
  = render 'api_response', :request => @bm_button_search, :response => @bm_button_search_response

samples/app/views/button_manager_samples/button_manager/bm_create_button.html.haml
= api_form_for @bm_create_button, :url => button_manager_path(:bm_create_button) do |f|

  .row
    .span5
      %legend Create button request
      = f.input :ButtonType
      = f.input :ButtonCode
      %legend For payment plan button
      = f.fields_for :OptionDetails do |opt|
        = opt.fields_for :OptionSelectionDetails do |det|
          = det.fields_for :PaymentPeriod do |per|
            = per.input :Amount
            = per.input :BillingFrequency
            = per.input :TotalBillingCycles
            = per.input :BillingPeriod
          = det.input :OptionType
    .span5
      %legend Button var
      .control-group
        %label.control-label{:for => "ButtonVar_item_name"} Item
        .controls= text_field_tag "ButtonVar[item_name]", @button_var["item_name"]
      .control-group
        %label.control-label{:for => "ButtonVar_amount"} Amount
        .controls= text_field_tag "ButtonVar[amount]", @button_var["amount"]
      .control-group
        %label.control-label{:for => "ButtonVar_return"} Return Url
        .controls= text_field_tag "ButtonVar[return]", @button_var["return"]
      .control-group
        %label.control-label{:for => "ButtonVar_notify_url"} Notify Url
        .controls= text_field_tag "ButtonVar[notify_url]", @button_var["notify_url"]
      .control-group
        %label.control-label{:for => "ButtonVar_shopping_url"} Shipping Url
        .controls= text_field_tag "ButtonVar[shopping_url]", @button_var["shopping_url"]
      .control-group
        %label.control-label{:for => "ButtonVar_min_amount"} Min Amount
        .controls= text_field_tag "ButtonVar[min_amount]", @button_var["min_amount"]
      .control-group
        %label.control-label{:for => "ButtonVar_subtotal"} Sub Total
        .controls= text_field_tag "ButtonVar[subtotal]", @button_var["subtotal"]

      %legend For Subscribe
      .control-group
        %label.control-label{:for => "ButtonVar_t3"} Billing cycle units
        .controls= select_tag "ButtonVar[t3]", options_for_select(["", "D", "W", "M", "Y"]), :value => @button_var["t3"]
      .control-group
        %label.control-label{:for => "ButtonVar_p3"} Billing cycle
        .controls= text_field_tag "ButtonVar[p3]", @button_var["p3"], :placeholder => "Ex: 1"
      .control-group
        %label.control-label{:for => "ButtonVar_a3"} Price
        .controls= text_field_tag "ButtonVar[a3]", @button_var["a3"], :placeholder => "Ex: 10.00"

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bm_create_button_response
  = render 'api_response', :request => @bm_create_button, :response => @bm_create_button_response
  = link_to "Email link", @bm_create_button_response.Email if @bm_create_button_response.Email

samples/app/views/button_manager_samples/button_manager/bm_get_button_details.html.haml
= api_form_for @bm_get_button_details, :url => button_manager_path(:bm_get_button_details) do |f|

  .row
    .span5
      %legend Get button details request
      = f.input :HostedButtonID

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bm_get_button_details_response
  = render 'api_response', :request => @bm_get_button_details, :response => @bm_get_button_details_response

samples/app/views/button_manager_samples/button_manager/bm_get_inventory.html.haml
= api_form_for @bm_get_inventory, :url => button_manager_path(:bm_get_inventory) do |f|

  .row
    .span5
      %legend Get inventory request
      = f.input :HostedButtonID

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bm_get_inventory_response
  = render 'api_response', :request => @bm_get_inventory, :response => @bm_get_inventory_response

samples/app/views/button_manager_samples/button_manager/bm_manage_button_status.html.haml
= api_form_for @bm_manage_button_status, :url => button_manager_path(:bm_manage_button_status) do |f|

  .row
    .span5
      %legend Manage button status request
      = f.input :HostedButtonID
      = f.input :ButtonStatus

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bm_manage_button_status_response
  = render 'api_response', :request => @bm_manage_button_status, :response => @bm_manage_button_status_response

samples/app/views/button_manager_samples/button_manager/bm_set_inventory.html.haml
= api_form_for @bm_set_inventory, :url => button_manager_path(:bm_set_inventory) do |f|

  .row
    .span5
      %legend Set inventory request
      = f.input :HostedButtonID
      = f.input :TrackInv
      = f.input :TrackPnl
      = f.fields_for :ItemTrackingDetails do |det|
        = det.input :ItemQty
        = det.input :ItemCost

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bm_set_inventory_response
  = render 'api_response', :request => @bm_set_inventory, :response => @bm_set_inventory_response

samples/app/views/layouts/button_manager_samples/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "#{service_action.humanize} | #{service_name.humanize}"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag    "button_manager_samples/application", :media => "all"
  %body
    = render "header"
    .container
      .row
        .span2= render "sidebar"
        .span10= yield
    = javascript_include_tag "button_manager_samples/application"